import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StickyCursor from "@/components/StickyCursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Ristorante Punto Verde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <StickyCursor />
        {children}
      </body>
    </html>
  );
}
