import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StickyCursor from "@/components/StickyCursor";
import { isMobileDevice } from "@/lib/mobileDetect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Ristorante Punto Verde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mobile = isMobileDevice();

  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Punto Verde" />
      </head>
      <body className={`${inter.className} dark`}>
        <StickyCursor isMobile={mobile} />
        {children}
      </body>
    </html>
  );
}
